### ISSUE TITLE
CODE REVIEW NEEDED

### ISSUE THREAD

**Issue by KristerBC** [PolytechLyon/tp-mvc-clasen-mvc#1]
Bonjour,

J'ai oublié à vous indiquer hier, que j'ai fini ce TP.

Je vous souhaite une bonne journée.

Bien cordialement,
Kristoffer.

**Comment by k33g** [comment]
Bonjour @KristerBC
très content que Vue.js vous plaise 😀
si vous avez besoin de plus d'éléments sur le sujet dites le moi

pour la partie https://github.com/PolytechLyon/tp-mvc-clasen-mvc/blob/master/RAPPORT.md#authentification, côté JavaScript vous feriez comment?

**Comment by KristerBC** [comment]
Bonjour @k33g,
Merci de votre proposition. Je vous dirai, si j'ai besoin de quelque chose concernant vue.js. Je vais sûrement regarder un peu plus en profondeur pendant les vacances d'été.

J'ai fait des correction sur cette partie, pour expliquer un peu mieux le fonctionnement.
